/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.hotelpulse;

import com.google.firebase.database.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.util.logging.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.*;
import javax.swing.table.*;

/**
 *
 * @author thanapon
 */
public class BookingFrame extends javax.swing.JFrame {
    private final DatabaseReference ref;
    /**
     * Creates new form CheckInFrame
     */
    public BookingFrame() {
        initComponents();
        
        FireBaseService fbs = null;

        try {
            fbs = new FireBaseService();
        } catch (IOException ex) {
            Logger.getLogger(BookingFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ref = fbs.getDb().getReference("booking");
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        checkinBtn = new javax.swing.JButton();
        checkoutBtn = new javax.swing.JButton();
        bookingBtn = new javax.swing.JButton();
        roomsBtn = new javax.swing.JButton();
        guestsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingT = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(189, 227, 255));

        checkinBtn.setBackground(new java.awt.Color(179, 179, 179));
        checkinBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        checkinBtn.setText("Check In");
        checkinBtn.setBorderPainted(false);
        checkinBtn.setFocusPainted(false);
        checkinBtn.setFocusable(false);
        checkinBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkinBtnMouseClicked(evt);
            }
        });
        checkinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinBtnActionPerformed(evt);
            }
        });

        checkoutBtn.setBackground(new java.awt.Color(179, 179, 179));
        checkoutBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        checkoutBtn.setText("Check Out");
        checkoutBtn.setBorderPainted(false);
        checkoutBtn.setFocusPainted(false);
        checkoutBtn.setFocusable(false);
        checkoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutBtnMouseClicked(evt);
            }
        });

        bookingBtn.setBackground(new java.awt.Color(117, 117, 117));
        bookingBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bookingBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookingBtn.setText("Booking");
        bookingBtn.setBorderPainted(false);
        bookingBtn.setEnabled(false);
        bookingBtn.setFocusPainted(false);
        bookingBtn.setFocusable(false);

        roomsBtn.setBackground(new java.awt.Color(179, 179, 179));
        roomsBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        roomsBtn.setText("Rooms");
        roomsBtn.setBorderPainted(false);
        roomsBtn.setFocusPainted(false);
        roomsBtn.setFocusable(false);
        roomsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomsBtnMouseClicked(evt);
            }
        });

        guestsBtn.setBackground(new java.awt.Color(179, 179, 179));
        guestsBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        guestsBtn.setText("Guests");
        guestsBtn.setBorderPainted(false);
        guestsBtn.setFocusPainted(false);
        guestsBtn.setFocusable(false);
        guestsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guestsBtnMouseClicked(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(242, 242, 242));
        backBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBtn.setFocusPainted(false);
        backBtn.setFocusable(false);
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(checkinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(bookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(roomsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(guestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        bookingT.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bookingT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Phone", "Passport", "Check-in", "Check-out", "Arriving Time", "Guests"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookingT.setFocusable(false);
        bookingT.setGridColor(new java.awt.Color(0, 0, 0));
        bookingT.setRowHeight(25);
        bookingT.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        bookingT.getTableHeader().setResizingAllowed(false);
        bookingT.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(bookingT);
        if (bookingT.getColumnModel().getColumnCount() > 0) {
            bookingT.getColumnModel().getColumn(0).setResizable(false);
            bookingT.getColumnModel().getColumn(1).setResizable(false);
            bookingT.getColumnModel().getColumn(2).setResizable(false);
            bookingT.getColumnModel().getColumn(3).setResizable(false);
            bookingT.getColumnModel().getColumn(4).setResizable(false);
            bookingT.getColumnModel().getColumn(5).setResizable(false);
            bookingT.getColumnModel().getColumn(6).setResizable(false);
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        if (bookingT.getColumnModel().getColumnCount() > 0) {
            bookingT.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
            bookingT.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
            bookingT.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
            bookingT.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
            bookingT.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
            bookingT.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
            bookingT.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
        }

        bookingT.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent evt) {
                if (bookingT.getSelectionModel().isSelectionEmpty()) {
                    editBtn.setEnabled(false);
                    removeBtn.setEnabled(false);
                } else {
                    editBtn.setEnabled(true);
                    removeBtn.setEnabled(true);
                }
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        addBtn.setBackground(new java.awt.Color(179, 179, 179));
        addBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addBtn.setText("Add");
        addBtn.setBorderPainted(false);
        addBtn.setFocusPainted(false);
        addBtn.setFocusable(false);
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(179, 179, 179));
        editBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editBtn.setText("Edit");
        editBtn.setBorderPainted(false);
        editBtn.setEnabled(false);
        editBtn.setFocusPainted(false);
        editBtn.setFocusable(false);
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });

        removeBtn.setBackground(new java.awt.Color(179, 179, 179));
        removeBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removeBtn.setText("Remove");
        removeBtn.setBorderPainted(false);
        removeBtn.setEnabled(false);
        removeBtn.setFocusPainted(false);
        removeBtn.setFocusable(false);
        removeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("Hotel Pulse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 909, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkinBtnActionPerformed

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    private void checkinBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkinBtnMouseClicked
        // TODO add your handling code here:
        CheckInFrame checkinFrame = new CheckInFrame();
        checkinFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkinBtnMouseClicked

    private void roomsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsBtnMouseClicked
        // TODO add your handling code here:
        RoomsFrame roomsFrame = new RoomsFrame();
        roomsFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_roomsBtnMouseClicked

    private void guestsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestsBtnMouseClicked
        // TODO add your handling code here:
        GuestsFrame guestsFrame = new GuestsFrame();
        guestsFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guestsBtnMouseClicked

    private void checkoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutBtnMouseClicked
        // TODO add your handling code here:
        CheckOutFrame checkoutFrame = new CheckOutFrame();
        checkoutFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkoutBtnMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        // TODO add your handling code here:
        AddBookingFrame addBookingFrame = new AddBookingFrame();
        addBookingFrame.setVisible(true);
        
        addBookingFrame.addWindowListener(new WindowListener() {
            @Override
            public void windowClosed(WindowEvent e) {
                updateTable();
            }

            @Override
            public void windowOpened(WindowEvent e) {}

            @Override
            public void windowClosing(WindowEvent e) {}

            @Override
            public void windowIconified(WindowEvent e) {}

            @Override
            public void windowDeiconified(WindowEvent e) {}

            @Override
            public void windowActivated(WindowEvent e) {}

            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
    }//GEN-LAST:event_addBtnMouseClicked

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        // TODO add your handling code here:
        EditBookingFrame editBookingFrame = new EditBookingFrame(
                bookingT.getModel().getValueAt(bookingT.getSelectedRow(), 0).toString(),
                bookingT.getModel().getValueAt(bookingT.getSelectedRow(), 1).toString(),
                bookingT.getModel().getValueAt(bookingT.getSelectedRow(), 2).toString(),
                bookingT.getModel().getValueAt(bookingT.getSelectedRow(), 3).toString(),
                bookingT.getModel().getValueAt(bookingT.getSelectedRow(), 4).toString(),
                bookingT.getModel().getValueAt(bookingT.getSelectedRow(), 5).toString(),
                bookingT.getModel().getValueAt(bookingT.getSelectedRow(), 6).toString()
        );
        editBookingFrame.setVisible(true);
        
        editBookingFrame.addWindowListener(new WindowListener() {
            @Override
            public void windowClosed(WindowEvent e) {
                updateTable();
            }

            @Override
            public void windowOpened(WindowEvent e) {}

            @Override
            public void windowClosing(WindowEvent e) {}

            @Override
            public void windowIconified(WindowEvent e) {}

            @Override
            public void windowDeiconified(WindowEvent e) {}

            @Override
            public void windowActivated(WindowEvent e) {}

            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
    }//GEN-LAST:event_editBtnMouseClicked

    private void removeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBtnMouseClicked
        // TODO add your handling code here:
        String[] options = {"No", "Yes"};
        int option = JOptionPane.showOptionDialog(null, "Are you sure to delete?", "Delete booking", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        
        if (option == 1) {
            ref.child(bookingT.getModel().getValueAt(bookingT.getSelectedRow(), 2).toString()).addListenerForSingleValueEvent(new ValueEventListener() {
                @Override
                public void onDataChange(DataSnapshot dataSnapshot) {
                    dataSnapshot.getRef().removeValue(new DatabaseReference.CompletionListener() {
                        @Override
                        public void onComplete(DatabaseError error, DatabaseReference ref1) {
                            updateTable();
                        }
                    });
                }
            
                @Override
                public void onCancelled(DatabaseError error) {
                    System.out.println("The read failed: " + error.getCode());
                }
            });
        }
    }//GEN-LAST:event_removeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingFrame().setVisible(true);
            }
        });
    }
    
    private void updateTable() {
        DefaultTableModel model = (DefaultTableModel) bookingT.getModel();
        model.setRowCount(0);
        
        ref.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                for (DataSnapshot ds : dataSnapshot.getChildren()) {
                    Guest booking = ds.getValue(Guest.class);
                    model.addRow(new Object[]{
                        booking.getName(),
                        booking.getPhone(),
                        booking.getPassport(),
                        booking.getIn(),
                        booking.getOut(),
                        booking.getArriving(),
                        booking.getGuests()
                    });
                }
            }

            @Override
            public void onCancelled(DatabaseError error) {
                System.out.println("The read failed: " + error.getCode());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton bookingBtn;
    private javax.swing.JTable bookingT;
    private javax.swing.JButton checkinBtn;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton guestsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton roomsBtn;
    // End of variables declaration//GEN-END:variables
}
